import "~/styles/globals.css";

import { type Metadata } from "next";
import { ThemeProvider } from "~/components/layout/theme-provider";
import { GeistSans as geistSans } from "geist/font/sans";

import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const overusedGrotesk = localFont({
  src: "./OverusedGrotesk-VF.woff2",
  variable: "--font-overused-grotesk",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${overusedGrotesk.variable}`}
      suppressHydrationWarning
    >
      <body className={geistSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
